branches:
    except:
        - gh-pages

environment:
    QTDIR: C:\Qt\5.4\mingw491_32
    MINGW_DIR: C:\Qt\Tools\mingw491_32 

install:
    - set PATH=%PATH%;%QTDIR%\bin;%MINGW_DIR%\bin
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - qmake ..\CuteMarkEd.pro

build_script:
    - mingw32-make

test_script:
    - cd test\unit
    - release\unittest.exe -nocrashhandler  
    - mingw32-make check

on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
